### PR TITLE
Presto for MMS

### PR DESCRIPTION
**Pull request by rusher81572**
Hello, @tzach 

Here is Presto for MMS

cd presto
docker build -t presto .
docker run --name presto --network mms_web -p 8080:8080 -d presto
 
Test that presto is running

http://127.0.0.1:8080

Execute queries:

docker exec -it presto bash

./presto-cli.jar --catalog cassandra

use catalog;
select * from mutant_data where first_name like 'Bob';

Return to http://127.0.0.1:8080 to see the queries from the web interface.

### CODE REVIEW

**Comment by dorlaor** [comment]
Looks like it's as simple as possible. NICE

**Comment by tzach** [comment]
Thanks @rusher81572 looks good!
Please add a meaningful README.md file, with everything one needs to run the example

**Comment by rusher81572** [comment]
@tzach updated README for MMS and added a README for Presto

**Comment by rusher81572** [comment]
@tzach may you please approve this?

**Pull request merged**
