### PR TITLE
repleacement old netty jar link

### PR DESCRIPTION
**Pull request by AdamStawarz**
The old path for netty repository is not exist anymore -->

404 - Path /io/netty/netty-all/4.0.56.Final-SNAPSHOT/netty-all-4.0.56.Final-20180202.121251-12.jar not found in local storage of repository "Snapshots" [id=snapshots]

replaced to: 
https://oss.sonatype.org/content/repositories/snapshots/io/netty/netty-all/4.0.57.Final-SNAPSHOT/netty-all-4.0.57.Final-20181019.121534-257.jar

### CODE REVIEW

**Comment by tarzanek** [comment]
@AdamStawarz can you check and update again?
I can merge once you will find new version, also ideally can this be abstracted to some generic link that would get a recent version?
e.g. can this be taken from maven? (it usually keeps jars longer)

**Comment by AdamStawarz** [comment]
@tarzanek changed and tested

**Comment by tarzanek** [comment]
if you tested, then I have no prob
(fwiw there is also https://repo1.maven.org/maven2/io/netty/netty-all/4.0.56.Final/ there)

**Comment by tarzanek** [comment]
@AdamStawarz 
fwiw guy already fixed it in https://github.com/scylladb/scylla-code-samples/blob/master/mms/java/Dockerfile
to the repo I pointed above :-D

**Comment by tarzanek** [comment]
closing as won't fix, since it's already fixed

**Pull request closed without merging**
