### PR TITLE
Spark Demo PR

### PR DESCRIPTION
**Pull request by rusher81572**
docker run -d -h spark --network mms_web --name=spark -d p7hb/docker-spark sleep infinity
docker exec -it spark /usr/local/spark-2.2.0-bin-hadoop2.7/sbin/start-thriftserver.sh \
--conf hive.server2.thrift.bind.host=0.0.0.0 \
--conf spark.cassandra.connection.host=scylla-node1 \
--packages datastax:spark-cassandra-connector:2.0.1-s_2.11

docker run -d -p 8088:8088 --network mms_web --name superset amancevice/superset:0.25.2
sleep 10
docker exec -it superset superset-init --username admin --firstname admin --lastname admin --email admin@admin.com --password admin
docker cp HiveSparkScylla_datasource.yaml superset:/home/superset/HiveSparkScylla_datasource.yaml
docker exec -it superset superset import_datasources -p HiveSparkScylla_datasource.yaml

#Create the Hive Table
#docker exec -it spark beeline 
#!connect jdbc:hive2://localhost:10000 -n -p
#CREATE TABLE tracking USING org.apache.spark.sql.cassandra OPTIONS (keyspace 'tracking', table 'tracking_data');

#Import dashboard.json into the Web Interface
# Manage -> Import Dashboards

### CODE REVIEW

**Comment by tzach** [comment]
@rusher81572 is this demo ready?
I do not see the superset docker

**Comment by rusher81572** [comment]
It is in the instructions, most of this demo is manual, spark image does not work in compose

**Comment by tzach** [comment]
why do spark does not work with compose? maybe I can find a way

**Comment by rusher81572** [comment]
it will keep restarting over and over with no logs =(

Phillip Tribble
phillip.tribble@gmail.com

**Comment by tzach** [comment]
Maybe because it opens a bash script at the end of the Docker file
https://github.com/P7h/docker-spark/blob/master/Dockerfile#L55

**Pull request merged**
