### PR TITLE
Add docker-compose.yaml for the ScyllaDB/Spark introduction post

### PR DESCRIPTION
**Pull request by iravid**

### CODE REVIEW

**Comment by iravid** [comment]
cc @tzach @dorlaor

**Comment by tzach** [comment]
@iravid please add two README.md files, one under `scylla-and-spark/` and one under `introduction/` giving some context on the example, and how to run it.
See https://github.com/scylladb/scylla-code-samples/tree/master/mms as an example

**Comment by iravid** [comment]
Sure! Will do

**Comment by iravid** [comment]
Sorry for the delay @tzach - added the `README` files

**Comment by tzach** [comment]
Thanks @iravid !

**Pull request merged**
