### PR TITLE
Updating README.md to include steps for Debian based installations an…

### PR DESCRIPTION
**Pull request by ivenn-scylladb**
…d some smaller fixes.

### CODE REVIEW

**Review by ivenn-scylladb — COMMENTED** [review]
Added consistencylevel variable.

**Comment by tarzanek** [comment]
please fix the config.yaml directly instead of readme @ivenn-scylladb

**Review by ivenn-scylladb — COMMENTED** [review]
Consistency level has been moved to config as requested

**Comment by tarzanek** [comment]
thnx @ivenn-scylladb , merging

**Pull request merged**
