### PR TITLE
fixing TWCS paramteres due to change from DateTiered to TimeWindow co…

### PR DESCRIPTION
**Pull request by guy9**
…mpaction strategies, also adding ttl and gc_grace.
This fixes issue #215

### CODE REVIEW

**Comment by tarzanek** [comment]
lgtm, merging, thnx

**Comment by tarzanek** [comment]
resp. this sets retention of mms to only 20h
(as per default_time_to_live = 72000 )
is it OK for the demo app?

maybe you can make the window 1 day and have 20 days TTL ? @guy9 ? (I lack mms app details, so not sure what is use case and if 20h are OK)

**Comment by tarzanek** [comment]
if semantics is ok, then please merge, syntactically it looks better and will work when running the demo
( cc @nopzdk thnx for the report/test)

**Comment by guy9** [comment]
Thanks!

**Pull request merged**
