### PR TITLE
move to docker hub image of scylla

### LINKED ISSUE #79: MMS example does not use standard Docker instance
instead, build its own Ubuntu base Scylla image
https://github.com/scylladb/scylla-code-samples/blob/master/mms/scylla/Dockerfile

Fix: use scylla image from docker hub in
https://github.com/scylladb/scylla-code-samples/blob/master/mms/docker-compose.yml
https://github.com/scylladb/scylla-code-samples/blob/master/mms/docker-compose-dc2.yml

### PR DESCRIPTION
**Pull request by tzach**
This PR drop usage of the local Docker built Scylla, and use the Docker hub Scylla image.
In the process, it drops the scripting and moved to attached volumes for config files.

Fix #79

### CODE REVIEW

**Comment by tzach** [comment]
This change will require an update to the MMS pages:
the use of `- IMPORT=IMPORT` was deprecated, for using `docker exec scylla-node1 cqlsh -f /mutant-data.txt`
For example here:
https://www.scylladb.com/2018/03/28/mms-day7-multidatacenter-consistency/
and maybe in more places

**Comment by tzach** [comment]
@guy9 @gnumoreno ping

**Comment by guy9** [comment]
After running "docker-compose up -d" the nodes keep restarting. 
When looking at the log this is what I see:

[guy@localhost mms]$ git log mms mms_scylla-node2_1
fatal: ambiguous argument 'mms': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
[guy@localhost mms]$ docker log mms mms_scylla-node2_1
docker: 'log' is not a docker command.
See 'docker --help'
[guy@localhost mms]$ docker logs mms mms_scylla-node2_1
"docker logs" requires exactly 1 argument(s).
See 'docker logs --help'.

Usage:  docker logs [OPTIONS] CONTAINER

Fetch the logs of a container
[guy@localhost mms]$ docker logs mms_scylla-node2_1
running: (['/usr/lib/scylla/scylla_dev_mode_setup', '--developer-mode', '1'],)
failed!
Traceback (most recent call last):
  File "/docker-entrypoint.py", line 15, in <module>
    setup.io()
  File "/scyllasetup.py", line 37, in io
    cfg = yaml.load(open(os.path.join(conf_dir, "scylla.yaml")))
PermissionError: [Errno 13] Permission denied: '/etc/scylla/scylla.yaml'
running: (['/usr/lib/scylla/scylla_dev_mode_setup', '--developer-mode', '1'],)
failed!
Traceback (most recent call last):
  File "/docker-entrypoint.py", line 15, in <module>
    setup.io()
  File "/scyllasetup.py", line 37, in io
    cfg = yaml.load(open(os.path.join(conf_dir, "scylla.yaml")))
PermissionError: [Errno 13] Permission denied: '/etc/scylla/scylla.yaml'
running: (['/usr/lib/scylla/scylla_dev_mode_setup', '--developer-mode', '1'],)
failed!
Traceback (most recent call last):
  File "/docker-entrypoint.py", line 15, in <module>
    setup.io()
  File "/scyllasetup.py", line 37, in io
    cfg = yaml.load(open(os.path.join(conf_dir, "scylla.yaml")))
PermissionError: [Errno 13] Permission denied: '/etc/scylla/scylla.yaml'
running: (['/usr/lib/scylla/scylla_dev_mode_setup', '--developer-mode', '1'],)
failed!
Traceback (most recent call last):
  File "/docker-entrypoint.py", line 15, in <module>
    setup.io()
  File "/scyllasetup.py", line 37, in io
    cfg = yaml.load(open(os.path.join(conf_dir, "scylla.yaml")))
PermissionError: [Errno 13] Permission denied: '/etc/scylla/scylla.yaml'
running: (['/usr/lib/scylla/scylla_dev_mode_setup', '--developer-mode', '1'],)
failed!
Traceback (most recent call last):
  File "/docker-entrypoint.py", line 15, in <module>
    setup.io()
  File "/scyllasetup.py", line 37, in io
    cfg = yaml.load(open(os.path.join(conf_dir, "scylla.yaml")))
PermissionError: [Errno 13] Permission denied: '/etc/scylla/scylla.yaml'
running: (['/usr/lib/scylla/scylla_dev_mode_setup', '--developer-mode', '1'],)
failed!
Traceback (most recent call last):
  File "/docker-entrypoint.py", line 15, in <module>
    setup.io()
  File "/scyllasetup.py", line 37, in io
    cfg = yaml.load(open(os.path.join(conf_dir, "scylla.yaml")))
PermissionError: [Errno 13] Permission denied: '/etc/scylla/scylla.yaml'
running: (['/usr/lib/scylla/scylla_dev_mode_setup', '--developer-mode', '1'],)
failed!
Traceback (most recent call last):
  File "/docker-entrypoint.py", line 15, in <module>
    setup.io()
  File "/scyllasetup.py", line 37, in io
    cfg = yaml.load(open(os.path.join(conf_dir, "scylla.yaml")))
PermissionError: [Errno 13] Permission denied: '/etc/scylla/scylla.yaml'
running: (['/usr/lib/scylla/scylla_dev_mode_setup', '--developer-mode', '1'],)
failed!
Traceback (most recent call last):
  File "/docker-entrypoint.py", line 15, in <module>
    setup.io()
  File "/scyllasetup.py", line 37, in io
    cfg = yaml.load(open(os.path.join(conf_dir, "scylla.yaml")))
PermissionError: [Errno 13] Permission denied: '/etc/scylla/scylla.yaml'
running: (['/usr/lib/scylla/scylla_dev_mode_setup', '--developer-mode', '1'],)
failed!
Traceback (most recent call last):
  File "/docker-entrypoint.py", line 15, in <module>
    setup.io()
  File "/scyllasetup.py", line 37, in io
    cfg = yaml.load(open(os.path.join(conf_dir, "scylla.yaml")))
PermissionError: [Errno 13] Permission denied: '/etc/scylla/scylla.yaml'
running: (['/usr/lib/scylla/scylla_dev_mode_setup', '--developer-mode', '1'],)
failed!
Traceback (most recent call last):
  File "/docker-entrypoint.py", line 15, in <module>
    setup.io()
  File "/scyllasetup.py", line 37, in io
    cfg = yaml.load(open(os.path.join(conf_dir, "scylla.yaml")))
PermissionError: [Errno 13] Permission denied: '/etc/scylla/scylla.yaml'

**Comment by guy9** [comment]
The above issue was local to my machine, solved by reinstalling docker

**Comment by tzach** [comment]
@guy9 this change affects many of the MMS examples in the blog.
For example, the instructions for uploading the example data is different.
This is why I suggest opening a new mms2 directory with the new Docker format.

**Pull request merged**
