### PR TITLE
mms/java: Use Maven instead of Ant

### PR DESCRIPTION
**Pull request by Lorak-mmk**
Converted mms/java to use Maven instead of Ant.
Updated READMEs to reflect the changes - and fixed previosly existing errors.

### CODE REVIEW

**Review by guy9 — COMMENTED** [review]
Looks good to me. When I run it I get the following warnings, is this expected?

[main] WARN com.datastax.driver.core.HostConnectionPool - Not using advanced port-based shard awareness with scylla-node3/172.18.0.4:9042 because we're missing port-based shard awareness port on the server
[main] WARN com.datastax.driver.core.HostConnectionPool - Not using advanced port-based shard awareness with scylla-node2/172.18.0.2:9042 because we're missing port-based shard awareness port on the server
[main] WARN com.datastax.driver.core.HostConnectionPool - Not using advanced port-based shard awareness with scylla-node1/172.18.0.3:9042 because we're missing port-based shard awareness port on the server

**Comment by Lorak-mmk** [comment]
Drivers behavior is correct as Scylla used here doesn't have shard aware port enabled in config (https://github.com/scylladb/scylla-code-samples/blob/master/mms/scylla/scylla.yaml - no `native_shard_aware_transport_port` field). Whether that's intended is another question - I'd guess that maybe this config was created for old versions of Scylla and never updated, so shard awareness was never enabled?
To fix this it should be enough to `native_shard_aware_transport_port: 19042` to configs -  `mms/scylla/scylla.yaml` and `mms/scylla/scylla-replace-node.yaml`

**Comment by guy9** [comment]
thanks

**Review by guy9 — APPROVED** [review]

**Comment by guy9** [comment]
@tzach  please merge

**Comment by guy9** [comment]
Thanks @Lorak-mmk , I already updated them :-)

**Pull request merged**
