### PR TITLE
Updating scylla version and mms dir rename

### PR DESCRIPTION
**Pull request by guy9**
Updated Scylla version to 3.0.10 and renamed MMS2 to MMS

### CODE REVIEW

**Comment by guy9** [comment]
@tzach please review

**Comment by tzach** [comment]
Found a few mentions of `mms2` in the new `mms` directory:

```
~/project/guy-code-samples (updating_scylla_version)$ find ./mms -type f | xargs grep mms2
./mms/README.md:docker exec -it mms2_scylla-node1_1 bash
./mms/README.md:docker exec -it mms2_scylla-node1_1 cqlsh
./mms/README.md:docker exec mms2_scylla-node1_1 cqlsh -f /mutant-data.txt
./mms/java/README.md:docker run -d --net=mms2_web --name some-java-app java-app
./mms/java/README.md:docker exec -it mms2_scylla-node1_1 cqlsh
./mms/spark/docker-compose.yaml:      name: mms2_web
```

**Comment by tzach** [comment]
This does not work for me
I try to follow the instruction on the new MMS README.MD file:
```
cd mms
docker-compose up -d
```
(so far so good)

```
docker exec -it mms2_scylla-node1_1 bash
Error: No such container: mms2_scylla-node1_1
```

Under mms dir, the names of the containers are mms_scylla-node1_1, mms_scylla-node2_1, mms_scylla-node3_1

**Comment by guy9** [comment]
@tzach Tzach, it seems like we are not looking at the same README.MD file.
Are you looking at the file in the branch?
https://github.com/guy9/scylla-code-samples/blob/updating_scylla_version/mms/README.md

Screenshot from 2019-10-16 15-48-29

Screenshot from 2019-10-16 15-49-07

**Comment by tzach** [comment]
@guy9 look at the screen capture, it include "docekr exec -it mms2_..."
You need to change the mms2 to mms or this will not wort
The created docekr under mms dir does not have a mms2 prefix

**Comment by guy9** [comment]
@tzach thanks, fixed, please review

**Pull request merged**
